# Generated by Django 4.1.5 on 2023-02-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ac", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketproduct",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
