# Generated by Django 4.1.2 on 2023-02-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ac", "0002_ticketproduct_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="transaction_identifier",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="merchant_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
