# Generated by Django 4.1.5 on 2023-02-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ac", "0003_paymentrecord_transaction_identifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="merchant_id",
            field=models.CharField(default="a", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="transaction_identifier",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
