# Generated by Django 4.1.2 on 2023-02-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ac", "0003_alter_paymentrecord_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="merchant_order_no",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="respond_type",
            field=models.CharField(default="JSON", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="version",
            field=models.CharField(default="2.0", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
