# Generated by Django 4.1.5 on 2023-01-15 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=8)),
                ("division", models.CharField(max_length=3)),
                ("area", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("club_number", models.IntegerField()),
                ("chinese_name", models.CharField(max_length=100)),
                ("english_name", models.CharField(max_length=100)),
                ("charter_date", models.DateField(blank=True, null=True)),
                (
                    "meeting_week",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "meeting_day",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                ("meeting_start", models.TimeField(blank=True, null=True)),
                ("meeting_end", models.TimeField(blank=True, null=True)),
                (
                    "website",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "facebook",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("language", models.CharField(max_length=255)),
                ("club_type", models.CharField(max_length=9)),
                (
                    "qualification",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "fee",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "abbr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "photo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "en_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.IntegerField(blank=True, null=True)),
                ("zipcode", models.IntegerField(blank=True, null=True)),
                (
                    "memo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.agency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("chinese_name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=60)),
                (
                    "achievement",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "member_no",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "line",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_name", models.CharField(max_length=255)),
                ("tw_name", models.CharField(max_length=255, null=True)),
                ("show_name", models.CharField(max_length=255)),
                ("en_description", models.TextField(null=True)),
                ("tw_description", models.TextField(null=True)),
                ("en_purpose", models.TextField(null=True)),
                ("tw_purpose", models.TextField(null=True)),
                ("en_overview", models.TextField(null=True)),
                ("tw_overview", models.TextField(null=True)),
                ("en_includes", models.JSONField(null=True)),
                ("tw_includes", models.JSONField(null=True)),
                ("en_form", models.JSONField(null=True)),
                ("tw_form", models.JSONField(null=True)),
            ],
            options={
                "unique_together": {("en_name",)},
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "en_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tw_title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectInclude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_name", models.CharField(max_length=255, null=True)),
                ("tw_name", models.CharField(max_length=255, null=True)),
                ("en_form", models.FileField(null=True, upload_to="en_form/")),
                ("tw_form", models.FileField(null=True, upload_to="tw_form/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="includes",
                        to="api.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Path",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_name", models.CharField(max_length=255)),
                ("tw_name", models.CharField(max_length=255)),
                ("show_name", models.CharField(max_length=255)),
                ("initialism", models.CharField(max_length=2)),
                ("en_description", models.TextField()),
                ("tw_description", models.TextField()),
            ],
            options={
                "unique_together": {("en_name",)},
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("print", models.IntegerField(blank=True, null=True)),
                ("batch", models.IntegerField(blank=True, null=True)),
                ("confirm", models.IntegerField(blank=True, null=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.agency",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.club",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.member",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.role",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField()),
                ("en_name", models.CharField(max_length=255)),
                ("tw_name", models.CharField(max_length=255)),
                ("is_elective", models.BooleanField()),
                ("elective_number", models.IntegerField()),
                ("is_old", models.BooleanField()),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="api.path",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="api.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tw_title", models.CharField(max_length=250)),
                (
                    "en_title",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("contents", models.TextField(blank=True, null=True)),
                ("agenda", models.TextField(blank=True, null=True)),
                ("countdown", models.DateField()),
                ("deadline", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "address2",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("vacancy", models.IntegerField()),
                ("standby", models.IntegerField()),
                (
                    "target",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("fee", models.CharField(max_length=150)),
                ("languages", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=10)),
                (
                    "cover_photo",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "link",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "memo",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("attachment", models.CharField(max_length=255)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.event",
                    ),
                ),
            ],
        ),
    ]
